# Generated by Django 6.0.4 on 2026-04-16 03:20

import django.db.models.deletion
import ingresos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('referencia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContadorIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ano', models.CharField(max_length=6, unique=True)),
                ('ultimo_numero', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente por revisión'), ('reparacion', 'En reparación'), ('revisado', 'Revisado'), ('autorizado', 'Autorizado'), ('reparado', 'Reparado'), ('entregado', 'Entregado'), ('devolucion', 'Devolución'), ('garantia', 'Garantía')], max_length=20)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_general', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='historial/')),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='ingresos.historialequipo')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=ingresos.models.ruta_imagen_serial)),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('orden', models.IntegerField(default=1)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_serial', to='ingresos.equipo')),
            ],
            options={
                'verbose_name': 'Imagen de serial',
                'verbose_name_plural': 'Imagenes de serial',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, db_index=True)),
                ('descripcion_dano', models.TextField()),
                ('paga_revision', models.BooleanField(default=False)),
                ('recibido_por', models.CharField(choices=[('cristian', 'Cristian Usuga')], default='', max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente por revisión'), ('reparacion', 'En reparación'), ('revisado', 'Revisado'), ('autorizado', 'Autorizado'), ('reparado', 'Reparado'), ('entregado', 'Entregado'), ('devolucion', 'Devolución'), ('garantia', 'Garantía')], db_index=True, default='pendiente', max_length=20)),
                ('numero_ingreso', models.CharField(blank=True, db_index=True, editable=False, max_length=10, unique=True)),
                ('es_garantia', models.BooleanField(default=False)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresos.equipo')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='ImagenIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=ingresos.models.ruta_imagen_ingreso)),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('orden', models.IntegerField(default=1)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='ingresos.ingreso')),
            ],
        ),
        migrations.AddField(
            model_name='historialequipo',
            name='ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresos.ingreso'),
        ),
    ]
