# Generated by Django 6.0.4 on 2026-04-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialequipo',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imagenhistorial',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imageningreso',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imagenserial',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
