# Generated by Django 6.0.4 on 2026-04-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0002_alter_historialequipo_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='archivado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='archivado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
