# Generated by Django 6.0.4 on 2026-04-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0003_ingreso_archivado_ingreso_archivado_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialequipo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente por revisión'), ('reparacion', 'En reparación'), ('revisado', 'Revisado'), ('autorizado', 'Autorizado'), ('reparado', 'Reparado'), ('entregado', 'Entregado'), ('devolucion', 'Devolución'), ('garantia', 'Garantía'), ('archivado', 'Archivado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente por revisión'), ('reparacion', 'En reparación'), ('revisado', 'Revisado'), ('autorizado', 'Autorizado'), ('reparado', 'Reparado'), ('entregado', 'Entregado'), ('devolucion', 'Devolución'), ('garantia', 'Garantía'), ('archivado', 'Archivado')], db_index=True, default='pendiente', max_length=20),
        ),
    ]
