# Generated by Django 6.0.4 on 2026-04-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0004_alter_historialequipo_estado_alter_ingreso_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contadoringreso',
            options={'verbose_name': 'Contador de Ingreso'},
        ),
        migrations.RemoveField(
            model_name='contadoringreso',
            name='mes_ano',
        ),
        migrations.AlterField(
            model_name='historialequipo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente por revisión'), ('reparacion', 'En reparación'), ('revisado', 'Revisado'), ('autorizado', 'Autorizado'), ('reparado', 'Reparado'), ('entregado', 'Entregado'), ('devolucion', 'Devolución'), ('garantia', 'Garantía')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente por revisión'), ('reparacion', 'En reparación'), ('revisado', 'Revisado'), ('autorizado', 'Autorizado'), ('reparado', 'Reparado'), ('entregado', 'Entregado'), ('devolucion', 'Devolución'), ('garantia', 'Garantía')], db_index=True, default='pendiente', max_length=20),
        ),
    ]
