# Generated by Django 6.0.4 on 2026-04-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0005_alter_contadoringreso_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Recibidor',
                'verbose_name_plural': 'Recibidores',
                'ordering': ['nombre'],
            },
        ),
    ]
