# Generated by Django 6.0.4 on 2026-04-19 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0006_recibidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='recibido_por_nuevo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingresos.recibidor', verbose_name='Recibido por'),
        ),
    ]
