# Generated by Django 6.0.4 on 2026-04-19 22:25
from django.db import migrations

def migrar_datos(apps, schema_editor):
    Recibidor = apps.get_model('ingresos', 'Recibidor')
    Ingreso = apps.get_model('ingresos', 'Ingreso')

    mapa = {
        'cristian': 'Cristian Usuga',
    }

    for valor, nombre in mapa.items():
        recibidor, _ = Recibidor.objects.get_or_create(nombre=nombre)
        Ingreso.objects.filter(recibido_por=valor).update(recibido_por_nuevo=recibidor)

class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0007_ingreso_recibido_por_nuevo'),
    ]

    operations = [
        migrations.RunPython(migrar_datos, migrations.RunPython.noop),
    ]