# Generated by Django 6.0.4 on 2026-04-19 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0009_finalizar_recibido_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion_trabajo', models.TextField(verbose_name='Descripción del trabajo')),
                ('valor', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='valor (COP)')),
                ('creado_en', models.DateField(auto_now_add=True)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='ingresos.ingreso')),
            ],
            options={
                'verbose_name': 'Reporte Técnico',
                'verbose_name_plural': 'Reporte Técnicos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
