# Generated by Django 6.0.4 on 2026-04-20 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0010_reportetecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, unique=True, verbose_name='Numero cuenta de cobro')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre cliente')),
                ('id_cedula', models.CharField(max_length=20, verbose_name='Cedula o NIT')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion cliente')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono o celular')),
                ('ciudad', models.CharField(max_length=30, verbose_name='ciuda de residencia')),
                ('forma_pago', models.CharField(default='Transferencia', max_length=50, verbose_name='Forma de pago')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_cobro', to='ingresos.ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCuentaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='cantidad')),
                ('concepto', models.TextField(verbose_name='Concepto de cobro')),
                ('valor_unitario', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='valor unitario (COP)')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_items', to='ingresos.cuentacobro')),
            ],
        ),
    ]
