# Generated by Django 6.0.4 on 2026-04-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0011_cuentacobro_itemcuentacobro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacobro',
            name='numero',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numero cuenta de cobro'),
        ),
    ]
