# Generated by Django 6.0.4 on 2026-04-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0012_alter_cuentacobro_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacobro',
            name='numero',
            field=models.PositiveIntegerField(editable=False, unique=True, verbose_name='Numero cuenta de cobro'),
        ),
    ]
